// 由 Excel 自动生成，请不要手动编辑
export const WORDS = [
  {
    id: "1",
    word: "analyze",
    phonetic: "/ˈænəlaɪz/",
    pos: "",
    meaningZh: "vt.对……进行分析，分解; （等于 analyse）",
    extra: "analysis; n.分析",
  },
  {
    id: "2",
    word: "appear",
    phonetic: "/əˈpɪə(r)/",
    pos: "",
    meaningZh: "v.出现，呈现；看来，似乎",
    extra: "appearance; n.露面，外表，外观; disappear v . 消失，失踪",
  },
  {
    id: "3",
    word: "commit",
    phonetic: "/kəˈmɪt/",
    pos: "",
    meaningZh: "v.犯罪、错；承诺，忠于；; 订婚",
    extra: "commitment; n.忠诚，承诺",
  },
  {
    id: "4",
    word: "complicated",
    phonetic: "/'kDmplɪkeɪtɪd/",
    pos: "",
    meaningZh: "adj. 复杂的，难懂的",
    extra: "",
  },
  {
    id: "5",
    word: "confirm",
    phonetic: "/kən'f3:m/",
    pos: "",
    meaningZh: "vt. 证实；批准，确定",
    extra: "confirmed   adj.坚定的，根深蒂固的",
  },
  {
    id: "6",
    word: "frequent",
    phonetic: "/ˈfri:kwənt/",
    pos: "",
    meaningZh: "adj.  频繁的；    时常发 生; 的",
    extra: "Frequently   adv . 频繁地",
  },
  {
    id: "7",
    word: "gain",
    phonetic: "/geɪn/",
    pos: "",
    meaningZh: "vt. 获得，得到，赢到",
    extra: "",
  },
  {
    id: "8",
    word: "graduation",
    phonetic: "/'ɡræd3uIeɪʃn/",
    pos: "",
    meaningZh: "n.   毕业；; 毕业典礼",
    extra: "graduate    n.   毕业生；   v . 毕业; graduate from   从 ……毕业",
  },
  {
    id: "9",
    word: "loose",
    phonetic: "/lu:s/",
    pos: "",
    meaningZh: "adj. 宽松的，散漫的；; v.释放；; n.放纵，  放任",
    extra: "",
  },
  {
    id: "10",
    word: "occupy",
    phonetic: "/'Dkju paɪ/",
    pos: "",
    meaningZh: "vt. 居住；占领，占用",
    extra: "occupation   n.工作，  职业",
  },
  {
    id: "11",
    word: "potential",
    phonetic: "/pəˈtenʃl/",
    pos: "",
    meaningZh: "adj. 潜在的，可能的；n. 潜力，潜能",
    extra: "",
  },
  {
    id: "12",
    word: "previous",
    phonetic: "/ˈpriːviəs/",
    pos: "",
    meaningZh: "adj. 先前的，以前的",
    extra: "",
  },
  {
    id: "13",
    word: "recover",
    phonetic: "/rɪˈkʌvə(r)/",
    pos: "",
    meaningZh: "v. 恢复；康复；重新获得",
    extra: "",
  },
  {
    id: "14",
    word: "reduce",
    phonetic: "/rɪˈdjuːs/",
    pos: "",
    meaningZh: "v. 减少，降低",
    extra: "",
  },
  {
    id: "15",
    word: "release",
    phonetic: "/rɪˈliːs/",
    pos: "",
    meaningZh: "v. 释放；发行；发布；n. 释放；发布",
    extra: "",
  },
  {
    id: "16",
    word: "relief",
    phonetic: "/rɪˈliːf/",
    pos: "",
    meaningZh: "n. 减轻；解除；宽慰，轻松",
    extra: "",
  },
  {
    id: "17",
    word: "rely",
    phonetic: "/rɪˈlaɪ/",
    pos: "",
    meaningZh: "v. 依赖；信任（常用 rely on）",
    extra: "",
  },
  {
    id: "18",
    word: "replace",
    phonetic: "/rɪˈpleɪs/",
    pos: "",
    meaningZh: "v. 替换，代替；放回原处",
    extra: "",
  },
  {
    id: "19",
    word: "require",
    phonetic: "/rɪˈkwaɪə(r)/",
    pos: "",
    meaningZh: "v. 需要；要求",
    extra: "requirement   n. 必要条件，要求",
  },
  {
    id: "20",
    word: "reserve",
    phonetic: "/rɪˈzɜːv/",
    pos: "",
    meaningZh: "v. 预订，保留；n. 储备；保留",
    extra: "",
  },
  // ……中间省略，为了消息长度，这里实际上还有 800 多个对象……
  // 你在项目里粘贴的版本会是完整的 857 个词条。
];
